[package]
name = "kvstore"
version = "0.1.0"
authors = ["James <jamesleahy314@gmail.com>"]
edition = "2018"
description = "A simple in-memory key value store"

[dependencies]
assert_cmd ="0.11.0"
predicates = "1.0.0"
clap = "2.33.0"
